BOX_IMAGE = "generic/ubuntu1904"

Vagrant.configure("2") do |config|
  config.vm.define "single" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
  config.vm.provision "shell", inline: <<-SHELL
  echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDC4TTpBK0qRlC+qGKccOnkjRS2LqC8ARGGaso2KNFbixZoJ0VkipD+kecM9WAZ6f6DTMcm/Ytmz4zdsk7+CN4Ha0a1ScYdEMLnLta7cjS+TjpkCdu+nvDthhay3/XDwRwWYVXJpF4uCV9F6k2KBVy+bd6ya5fgc8RrryKNMJLHCRvthKYTwd/VOUiUGvSMtJTasf817ixPbLN1sxzDFJFULMJpwPdPBQ4pm8XOeSpDxdTOI0L0QT3zgKPybTzHHwlFXyjV+PsaELPRuo5kryYSq98290b9NcAbOYOueRREdqUSj0FucZrelK/gQTWhh2v3C/JTV3b9Er6vkY8c/v07 alexey@work-mbp.local" >> .ssh/authorized_keys
  SHELL
  end
end
