BOX_IMAGE = "centos/7"

Vagrant.configure("2") do |config|
  config.vm.define "single" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
  config.vm.provision "shell", inline: <<-SHELL
  echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCx55CrMqwwkmvF4zY7TOEI/xPMyVWanGeOXSjxDFlqJCxDvJCWNN6+8Cq5aja6mEBnSHzWoF2ciTUh+Y6E8QL9SxA8zB8JNPrD7/u7gA4iCkQIfmybWelOtm/Xpho3bYpF9r5Do53Z3YAlPyWcYaHqIeA3uMBGHlN5mrvxGhS5LA71d4MJDBfbCsybSk5CibmV5CLSIlbAxFuNU4fDIFZnRAHKF1iRAGpbsHI39uMXpt2LeYXHcOER8WOlJxAXhapX9YF26T0a8NxevC8hhKMzOrKvA1arqBIigTTDcxF6HGGf4ghpUnFExobL4W479pC74QPEDndtHLJ6Ge/PD/wZ alexey@alexhost" >> .ssh/authorized_keys
  SHELL
  end
end
