version: "3"

services:

    elasticsearch:
      image: elasticsearch:7.0.0
      volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        - ./elk_data:/usr/share/elasticsearch/data:rw
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        TZ: 'Europe/Moscow'
        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      networks:
        - elk

    logstash:
      image: logstash:7.0.0
      ports:
        - "5000:5000"
        - "9600:9600"
      volumes:
        - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
        - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      environment:
        TZ: 'Europe/Moscow'
        LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      networks:
        - elk
      depends_on:
        - elasticsearch

    kibana:
      image: kibana:7.0.0
      volumes:
        - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      ports:
        - "5601:5601"
      environment:
        TZ: 'Europe/Moscow'
      networks:
        - elk
      depends_on:
        - elasticsearch

networks: 
  elk:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '10.10.10.1/16'    
