---

#restart loadbalancer
- hosts: loadbalancer
  become: true
  tasks:
    - name: ensure nginx started
      service: name=nginx state=started enabled=yes

#webserver restart
- hosts: webserver
  become: true
  tasks:
    - name: ensure apache2 started
      service: name=apache2 state=started enabled=yes

#restart database
- hosts: database
  become: true
  tasks:
    - name: ensure mysql started
      service: name=mysql state=started enabled=yes




