---
- hosts: webserver
  become: yes

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: present

    - name: enable systemd
      service:
        name: apache2
        state: started
        enabled: yes
    
    - name: Add PHP 7.1 repo
      apt_repository:
        repo: 'ppa:ondrej/php'
        state: present

    - name: install php 7 packages
      apt: 
        pkg: "{{ item }}"
        update_cache: yes
        state: present 
      with_items:
        - php7.1 
        - php7.1-xml 
        - php7.1-mbstring 
        - php7.1-mysql 
        - php7.1-json 
        - php7.1-curl 
        - php7.1-cli 
        - php7.1-common 
        - php7.1-mcrypt 
        - php7.1-gd 
        - libapache2-mod-php7.1 
        - php7.1-zip
      notify: restart apache


