---
- hosts: webservers
  become: yes
  tasks:
    - name: install apache2
      update_cache: yes
      state: present
    - name: enable systemd
      service:
        name: apache2
        state: started
        enabled: yes


